insert into navigation_items(label,href,location,sort_order,status) values
('Expertise','/expertise','header',1,'published'),('Sectors','/sectors','header',2,'published'),('Intelligence','/intelligence','header',3,'published'),('Ask JAR','/ask-jar','header',4,'published'),('About Us','/about','header',5,'published'),('Contact','/contact','header',6,'published') on conflict do nothing;
insert into expertise_items(title,slug,summary,icon_key,sort_order,is_featured,status,published_at) values
('Strategic Advisory','strategic-advisory','Strategy, market entry, operating models and growth for complex regulated environments.','Compass',1,true,'published',now()),('AI & Intelligent Systems','ai-intelligent-systems','AI strategy, solution design and automation for smarter decisions and operations.','Brain',2,true,'published',now()),('Research & Intelligence','research-intelligence','Deep research and analytics that uncover insights and inform winning strategies.','Search',3,true,'published',now()),('Gamification & Engagement','gamification-engagement','Designing engaging experiences that drive participation, loyalty and impact.','Gamepad2',4,true,'published',now()),('Digital Transformation','digital-transformation','Modern platforms, process re-imagination and scalable digital solutions.','Layers',5,true,'published',now()),('Policy & Governance','policy-governance','Policy design, regulatory advisory and governance frameworks for sustainable outcomes.','Landmark',6,true,'published',now()) on conflict (slug) do nothing;
insert into ask_jar_prompts(prompt,category,sort_order,status,published_at) values
('How can AI improve a lottery ecosystem?','AI',1,'published',now()),('Trends in digital participation systems?','Participation',2,'published',now()),('Regulatory risks in iGaming markets?','Regulatory',3,'published',now()),('Strategies for player engagement?','Engagement',4,'published',now()) on conflict do nothing;
insert into metrics(label,value,description,icon_key,sort_order,status,published_at) values
('Countries','30+','Global reach across public and private sectors','Globe',1,'published',now()),('Public Sector Engagements','150+','Across multiple mandates and agencies','Landmark',2,'published',now()),('Years of Experience','25+','Deep domain expertise that delivers impact','TrendingUp',3,'published',now()),('Strategic Projects','500+','Delivered with measurable outcomes','Users',4,'published',now()) on conflict do nothing;
insert into site_sections(section_key,eyebrow,headline,subheadline,primary_cta_label,primary_cta_href,secondary_cta_label,secondary_cta_href,status,published_at) values
('home.hero','Strategic Advisory for a Changing World','Intelligence. Strategy. Real Impact.','JAR Advisory partners with governments, enterprises and visionary leaders to navigate complexity, build intelligent solutions and deliver enduring impact in regulated and high-stakes environments.','Explore Our Expertise','/expertise','Ask JAR','/ask-jar','published',now()) on conflict (section_key) do nothing;
